### ISSUE TITLE
Add email to subscription email messages

### ISSUE THREAD

**Issue by LeoOosterloo** [pronamic/wp-orbis-notifications#2]
Currently, only the subscription contact will receive email notifications based on subscription usage.

Can we add an option to have a fixed email address as a recipient? So that we also get an email when 100% of the subscription is used?

In our own case I want to add support@pronamic.nl as a recipient.

@rvdsteege can you look in to this?

**Comment by rvdsteege** [comment]
I've added a setting "Additional recipient for 100% quota notifications" to the Orbis settings page (**WordPress admin → Orbis → Settings**) where an email address can be set as additional recipient (this requires a WordPress user with the email address as the notifications work with users).

**Comment by LeoOosterloo** [comment]
Thank you @rvdsteege that looks good.
